#!/usr/bin/env python3
"""Write a URDF package (XML + per-part STL meshes) from a DesignResult."""

from __future__ import annotations

import math
from pathlib import Path
from typing import Any
from xml.sax.saxutils import escape

import numpy as np

from cad_pipeline.joints import root_links
from cad_pipeline.kinematics import link_world_origins_mm
from cad_pipeline.runtime import DesignResult, export_stl, _safe_part_filename

MM_TO_M = 0.001


def _xml_name(name: str) -> str:
    return escape(_safe_part_filename(name))


def _fmt_vec(vec: tuple[float, float, float] | np.ndarray) -> str:
    return " ".join(f"{float(v):.6g}" for v in vec)


def _part_volume_mm3(part: Any) -> float:
    try:
        from OCP.BRepGProp import BRepGProp
        from OCP.GProp import GProp_GProps

        solid = part.solid
        obj = solid.val() if hasattr(solid, "val") else solid
        shape = obj.wrapped if hasattr(obj, "wrapped") else obj
        props = GProp_GProps()
        BRepGProp.VolumeProperties_s(shape, props)
        return abs(float(props.Mass()))
    except Exception:
        verts = np.asarray(part.vertices, dtype=np.float64)
        size = verts.max(axis=0) - verts.min(axis=0)
        return float(max(size[0] * size[1] * size[2], 1.0))


def _inertial_xml(part: Any, indent: str) -> str:
    verts = np.asarray(part.vertices, dtype=np.float64)
    size_m = (verts.max(axis=0) - verts.min(axis=0)) * MM_TO_M
    size_m = np.maximum(size_m, 1e-4)
    volume_m3 = _part_volume_mm3(part) * 1e-9
    mass = max(volume_m3 * 1000.0, 1e-4)  # ~1 g/cm³
    # Solid box inertia about center
    x, y, z = (float(size_m[0]), float(size_m[1]), float(size_m[2]))
    ixx = mass * (y * y + z * z) / 12.0
    iyy = mass * (x * x + z * z) / 12.0
    izz = mass * (x * x + y * y) / 12.0
    return (
        f"{indent}<inertial>\n"
        f"{indent}  <origin xyz=\"0 0 0\" rpy=\"0 0 0\"/>\n"
        f"{indent}  <mass value=\"{mass:.6g}\"/>\n"
        f"{indent}  <inertia ixx=\"{ixx:.6g}\" ixy=\"0\" ixz=\"0\" "
        f"iyy=\"{iyy:.6g}\" iyz=\"0\" izz=\"{izz:.6g}\"/>\n"
        f"{indent}</inertial>"
    )


def _link_world_origins_mm(result: DesignResult) -> dict[str, tuple[float, float, float]]:
    return link_world_origins_mm(result)


def render_urdf_xml(
    result: DesignResult,
    *,
    robot_name: str,
    mesh_relpaths: dict[str, str],
) -> str:
    names = result.part_names()
    joints = list(result.joints)
    world = _link_world_origins_mm(result)
    roots = root_links(names, joints)
    lines = [
        '<?xml version="1.0"?>',
        f'<robot name="{escape(_safe_part_filename(robot_name))}">',
        "  <!-- Generated by AgentCAD. Units: meters. Meshes are millimetre STL × 0.001. -->",
        "  <!-- Only joints() relations are written. Unrelated parts are not welded. -->",
    ]
    if len(roots) > 1:
        lines.append(
            f"  <!-- Free-floating roots (not welded together): {', '.join(roots)} -->"
        )

    for name in names:
        part = result.parts[name]
        link = _xml_name(name)
        mesh = escape(mesh_relpaths[name])
        origin_m = tuple(v * MM_TO_M for v in world[name])
        visual_xyz = (-origin_m[0], -origin_m[1], -origin_m[2])
        origin_attr = _fmt_vec(visual_xyz)
        lines.append(f'  <link name="{link}">')
        lines.append(_inertial_xml(part, "    "))
        for tag in ("visual", "collision"):
            lines.append(f"    <{tag}>")
            lines.append(f'      <origin xyz="{origin_attr}" rpy="0 0 0"/>')
            lines.append("      <geometry>")
            lines.append(
                f'        <mesh filename="{mesh}" scale="{MM_TO_M} {MM_TO_M} {MM_TO_M}"/>'
            )
            lines.append("      </geometry>")
            lines.append(f"    </{tag}>")
        lines.append("  </link>")

    for joint in joints:
        parent_w = np.asarray(world[joint.parent], dtype=np.float64)
        child_w = np.asarray(world[joint.child], dtype=np.float64)
        xyz_m = tuple((child_w - parent_w) * MM_TO_M)
        jname = _xml_name(joint.name)
        lines.append(f'  <joint name="{jname}" type="{joint.type}">')
        lines.append(f'    <parent link="{_xml_name(joint.parent)}"/>')
        lines.append(f'    <child link="{_xml_name(joint.child)}"/>')
        lines.append(f'    <origin xyz="{_fmt_vec(xyz_m)}" rpy="{_fmt_vec(joint.rpy)}"/>')
        if joint.is_moving():
            lines.append(f'    <axis xyz="{_fmt_vec(joint.axis)}"/>')
            if joint.type != "continuous":
                lower = joint.lower
                upper = joint.upper
                if lower is None or upper is None:
                    if joint.type == "prismatic":
                        lower = -0.05 if lower is None else lower * MM_TO_M
                        upper = 0.05 if upper is None else upper * MM_TO_M
                    else:
                        lower = -math.pi if lower is None else lower
                        upper = math.pi if upper is None else upper
                elif joint.type == "prismatic":
                    # Agent specifies prismatic limits in millimetres
                    lower = lower * MM_TO_M
                    upper = upper * MM_TO_M
                lines.append(
                    f'    <limit lower="{lower:.6g}" upper="{upper:.6g}" '
                    f'effort="{joint.effort:.6g}" velocity="{joint.velocity:.6g}"/>'
                )
        lines.append("  </joint>")

    lines.append("</robot>")
    return "\n".join(lines) + "\n"


def export_urdf(
    result: DesignResult,
    dest: Path,
    *,
    robot_name: str | None = None,
    tolerance: float = 0.1,
    angular_tolerance: float = 0.1,
) -> tuple[Path, Path, list[Path]]:
    """
    Write a URDF package directory.

    dest may be a folder, or a path ending in .urdf (folder = dest.stem beside it
    or dest.parent / dest.stem).

    Returns (package_dir, urdf_path, mesh_paths).
    """
    dest = dest.expanduser().resolve()
    if dest.suffix.lower() == ".urdf":
        package = dest.parent / dest.stem
        robot = dest.stem
    else:
        package = dest
        robot = dest.name
    if robot_name:
        robot = robot_name
    meshes_dir = package / "meshes"
    package.mkdir(parents=True, exist_ok=True)
    meshes_dir.mkdir(parents=True, exist_ok=True)
    for old in meshes_dir.glob("*.stl"):
        old.unlink()

    mesh_paths: list[Path] = []
    mesh_rel: dict[str, str] = {}
    for name, part in result.parts.items():
        safe = _safe_part_filename(name)
        path = meshes_dir / f"{safe}.stl"
        export_stl(
            part.solid,
            path,
            tolerance=tolerance,
            angular_tolerance=angular_tolerance,
        )
        mesh_paths.append(path)
        mesh_rel[name] = f"meshes/{safe}.stl"

    urdf_path = package / f"{_safe_part_filename(robot)}.urdf"
    urdf_path.write_text(
        render_urdf_xml(result, robot_name=robot, mesh_relpaths=mesh_rel),
        encoding="utf-8",
    )
    return package, urdf_path, mesh_paths
